- name: "Configure gnome-terminal"
  hosts: "*"
  tasks:
    - name: "Ensure dconf-cli is present"
      ansible.builtin.apt:
        name: dconf-cli
        state: present
    - name: "Update settings using dconf"
      ansible.builtin.shell:
        cmd: dconf load /org/gnome/terminal/legacy/
        stdin: |
          [/]
          default-show-menubar=false

          [profiles:]
          default='b1dcc9dd-5262-4d8d-a863-c897e6d979b9'
          list=['b1dcc9dd-5262-4d8d-a863-c897e6d979b9']

          [profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
          audible-bell=false
          background-color='#282A36'
          bold-color='#6E46A4'
          bold-color-same-as-fg=true
          bold-is-bright=true
          cursor-colors-set=false
          default-size-columns=156
          default-size-rows=52
          font='JetBrainsMono Nerd Font 11'
          foreground-color='#F8F8F2'
          highlight-colors-set=false
          login-shell=false
          palette=['#262626', '#E356A7', '#42E66C', '#E4F34A', '#9B6BDF', '#E64747', '#75D7EC', '#EFA554', '#7A7A7A', '#FF79C6', '#50FA7B', '#F1FA8C', '#BD93F9', '#FF5555', '#8BE9FD', '#FFB86C']
          use-system-font=false
          use-theme-colors=false
          use-theme-transparency=true
